# æ­¤æ–‡ä»¶ä¿å­˜çš„æ˜¯æ•´ä¸ª jekyll é¡¹ç›®çš„æ‰€æœ‰é…ç½®é¡¹ï¼Œé…ç½®å¥½äº†ä¹‹ååŸºæœ¬å°±ä¸éœ€è¦å†æ›´æ”¹äº†

# ---------------- #
#   ä¸»è¦é…ç½®ä¿¡æ¯     #
# ---------------- #
baseurl: ""
url: http://blog.lingdongkuaichuan.com
date_format: "ordinal"
title: Mr.Zhouçš„åšå®¢
subtitle: "ğŸ˜’ğŸ˜’ğŸ˜’ã€‚ã€‚ã€‚ã€‚ã€‚ã€‚"
description: "å‘¨åšæ–‡çš„ä¸ªäººåšå®¢"
keywords: å‘¨åšæ–‡, è½¯ä»¶å¼€å‘å·¥ç¨‹å¸ˆ, å®‰å“ç§»åŠ¨ç«¯ï¼Œå‰ç«¯
# ç½‘ç«™ç½‘å€æ å±•ç¤ºçš„å›¾æ ‡
favicon: /favicon.ico
encoding: "utf-8"
side_bar_repo_limit: 5

# ---------------- #
#     ä½œè€…ä¿¡æ¯      #
# ---------------- #
author: å‘¨åšæ–‡
# å…¬å¸åç§° ç½‘ç«™
organization: å…±æµç§‘æŠ€
organization_url: http://www.xbrother.com
github_username: zhoubowen-sky
location: æ·±åœ³, ä¸­å›½
email: 1784225410@qq.com

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: é¦–é¡µ

  -
    href: /categories/
    label: åˆ†ç±»

  -
    href: /wiki/
    label: ç»´åŸº

  -
    href: /about/
    label: å…³äº

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 8
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
gems:
    - jekyll-github-metadata
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
#     - jekyll-mentions
collections:
    wiki:
        output: true
        permalink: /wiki/:path/

# ç½‘é¡µä¸Šçš„å¼€æºé¡¹ç›®å—æ¬¢è¿ç¨‹åº¦çš„æ’è¡Œ
repository: zhoubowen-sky/zhoubowen-sky.github.io
